=== ablvebird/Dark-Cruds-3/resources/bosses.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <!--Simple-->
    <xsd:element name="bossName" type="xsd:string"/>
    <xsd:element name="location" type="xsd:string"/>
    <xsd:element name="HP" type="xsd:integer"/>
    <xsd:element name="Poise" type="xsd:decimal"/>
    <xsd:element name="Souls" type="xsd:integer"/>
    <xsd:element name="dropName" type="xsd:string"/>
    <xsd:element name="description" type="xsd:string"/>

    <!--Complex-->
    <xsd:element name="stats">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="HP"/>
                <xsd:element ref="Poise"/>
                <xsd:element ref="Souls"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="drop">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="dropName"/>
                <xsd:element ref="description"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="boss">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="bossName"/>
                <xsd:element ref="location"/>
                <xsd:element ref="stats"/>
                <xsd:element ref="drop"/>
            </xsd:sequence>
            <xsd:attribute ref="bossId"/>
        </xsd:complexType>
    </xsd:element>

    <!--Attributes-->
    <xsd:attribute name="bossId" type="xsd:integer"/>

    <!--Root-->
    <xsd:element name="bosses">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="boss" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== ablvebird/Dark-Cruds-3/src/bosses.xml
<?xml version="1.0" encoding="UTF-8"?>
<bosses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bosses.xsd">
    <boss id="1">
        <bossName>Iudex Gundyr</bossName>
        <location>Cemetery of Ash</location>
        <stats>
            <HP>1037</HP>
            <Poise>185.00</Poise>
            <Souls>3000</Souls>
        </stats>
        <drops>
            <drop>
                <name>Coiled Sword</name>
                <description>
                    Sword missing from the shrine bonfire.
                    Cannot be equipped as a weapon.

                    Thrust into the shrine bonfire to restore its power and enable travel between bonfires.

                    This sword is only bequeathed to chosen ash, as judged by the Iudex, who awaits the arrival of ash as a scabbard.
                </description>
            </drop>
        </drops>
</bosses>
